# Generated by Django 5.2.4 on 2025-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("settled", models.BooleanField(default=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("settlement_date", models.DateField(blank=True, null=True)),
                ("task_id", models.CharField(max_length=25, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stripe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "STRIPE_PUBLIC_KEY",
                    models.CharField(blank=True, max_length=155, null=True),
                ),
                (
                    "STRIPE_SECRET_KEY",
                    models.CharField(blank=True, max_length=155, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
