# Generated by Django 5.2.4 on 2025-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='explanation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
