# Generated by Django 5.2.4 on 2025-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_chatmessage_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
