# Generated by Django 5.2.4 on 2025-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='marketing_emails', to='shop.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
